name: Develop variables

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: step 1
        env:
        DEV_USER: ${{ secrets.DEV_USER }}
        DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
        DEV_HOST: ${{ secrets.DEV_HOST }}
        DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
        PORT: ${{ secrets.PORT }}