name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dev-back-startamericas" #Must be unique in Heroku
          heroku_email: "ucb.start.project@gmail.com"

  deploy-develop:
    name: Deploy to Develop
    environment:
      name: Develop
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing using ${{ secrets.DB_USER }}
      
      - name: create env file
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env


  create-envfile:
    runs-on: ubuntu-latest
    environment:
      name: Develop
    steps:
    - name: Make env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_USER: ${{ secrets.B_USE }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
        file_name: .env