
name: Deploy

on:
  push:
    branches:
      - test-service


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-american-together"
          heroku_email: "ucb.start.project@gmail.com"